# PumpStation-v0:
#   normalize: true
#   n_envs: 1
#   policy: 'MlpPolicy'
#   n_timesteps: !!float 50000
#   batch_size: 256
#   n_steps: 8
#   gamma: 0.9999
#   learning_rate: 5.05041e-05
#   ent_coef: 0.000585045
#   clip_range: 0.1
#   n_epochs: 20
#   gae_lambda: 0.95
#   max_grad_norm: 1
#   vf_coef: 0.871923


PumpStation-v0: 
    policy: 'MlpPolicy'
    normalize: true
    n_timesteps: 50000
    batch_size: 128
    n_steps: 2048
    gamma: 0.9999
    learning_rate: 0.0008868604628397997
    ent_coef: 5.51072732865457e-06
    clip_range: 0.2 
    n_epochs: 10 
    gae_lambda: 0.9
    max_grad_norm: 0.7
    vf_coef: 0.4663195286157188
    sde_sample_freq: 32
    # log_std_init: 0.009632546502040817
    # activation_fn: 'tanh'
    # net_arch: 'medium'

# {'batch_size': 128, 
# 'n_steps': 2048, 
# 'gamma': 0.9999, 
# 'learning_rate': 0.0008868604628397997, 
# 'ent_coef': 5.51072732865457e-06, 
# 'clip_range': 0.2, 
# 'n_epochs': 10, 
# 'gae_lambda': 0.9, 
# 'max_grad_norm': 0.7, 
# 'vf_coef': 0.4663195286157188, 
# 'net_arch': 'tiny', 
# 'log_std_init': -2.5861223764945844, 
# 'sde_sample_freq': 32, 
# 'activation_fn': 'tanh'}

# {'batch_size': 256, 
# 'n_steps': 64, 
# 'gamma': 0.98, 
# 'learning_rate': 0.010793391045336956, 
# 'ent_coef': 7.02815680218493e-07, 
# 'clip_range': 0.1, 'n_epochs': 1, 'gae_lambda': 0.9, 
# 'max_grad_norm': 1, 
# 'vf_coef': 0.03538866484772407, 'net_arch': 'medium', 
# 'activation_fn': 'tanh'}

# {'batch_size': 512, 
# 'n_steps': 64, 
# 'gamma': 0.98, 
# 'learning_rate': 0.0004715401932112559, 
# 'ent_coef': 0.027689213719844546, 
# 'clip_range': 0.2, 
# 'n_epochs': 20, 
# 'gae_lambda': 0.92, 
# 'max_grad_norm': 0.7, 
# 'vf_coef': 0.9123561874119246, 
# 'net_arch': 'medium', 
# 'log_std_init': 0.009632546502040817, 
# 'sde_sample_freq': 32, 
# 'activation_fn': 'tanh'}
PumpStation3P-v0: 
    policy: 'MlpPolicy'
    normalize: true
    n_timesteps: 100000
    batch_size: 16
    n_steps: 32
    gamma: 0.99
    learning_rate: 0.11792137268597046
    ent_coef: 2.3273519905425797e-08
    clip_range: 0.1
    n_epochs: 5 
    gae_lambda: 0.92
    max_grad_norm: 1.0
    vf_coef: 0.7710790312272505
    sde_sample_freq: 64
    # log_std_init: 0.009632546502040817
    # activation_fn: 'tanh'
    # net_arch: 'medium'

# {'batch_size': 32, 
# 'n_steps': 2048, 
# 'gamma': 0.9999, 
# 'learning_rate': 0.0006695401941925542, 
# 'ent_coef': 7.597221505856992e-06, 
# 'clip_range': 0.3, 
# 'n_epochs': 10, 
# 'gae_lambda': 0.98, 
# 'max_grad_norm': 0.9, 
# 'vf_coef': 0.3334868969167528, 
# 'net_arch': 'small', 
# 'log_std_init': -1.6077663268434326, 
# 'sde_sample_freq': 32, 
# 'activation_fn': 'tanh'}



# {'batch_size': 256, 
# 'n_steps': 1024, 
# 'gamma': 0.9, 
# 'learning_rate': 0.008473911933178535, 
# 'ent_coef': 7.825929608116082e-07, 
# 'clip_range': 0.2, 'n_epochs': 5, 
# 'gae_lambda': 0.95, 'max_grad_norm': 0.8, 
# 'vf_coef': 0.923648223365816, 
# 'net_arch': 'tiny', 'log_std_init': -0.7068013958588906, 
# 'sde_sample_freq': 32, 
# 'activation_fn': 'tanh'}

PumpStation3P-power-v0: 
    policy: 'MlpPolicy'
    normalize: true
    n_timesteps: 100000
    batch_size: 16
    n_steps: 32
    gamma: 0.99
    learning_rate: 0.11792137268597046
    ent_coef: 2.3273519905425797e-08
    clip_range: 0.1
    n_epochs: 5 
    gae_lambda: 0.92
    max_grad_norm: 1.0
    vf_coef: 0.7710790312272505
    sde_sample_freq: 64
    # log_std_init: 0.009632546502040817
    # activation_fn: 'tanh'
    # net_arch: 'medium'


# PumpStation3P-power-v1:
#     policy: 'MlpPolicy'
#     normalize: true
#     n_timesteps: 100000
#     batch_size: 32
#     n_steps: 512
#     gamma: 0.99
#     learning_rate: 0.00016337737503832267
#     ent_coef: 0.016018769714559872
#     clip_range: 0.2
#     n_epochs: 10
#     gae_lambda: 0.98
#     max_grad_norm: 0.5
#     vf_coef: 0.36391931337035954
#     sde_sample_freq: 64
#     policy_kwargs: "dict(activation_fn=th.nn.Tanh, net_arch=[dict(pi=[64, 64], vf=[64, 64])])"

# PumpStation3P-power-v1:
#     policy: 'MlpPolicy'
#     normalize: true
#     n_timesteps: 100000
#     batch_size: 512
#     n_steps: 64
#     gamma: 0.95
#     learning_rate: 0.0005552121570231776
#     ent_coef: 0.08087141098702573
#     clip_range: 0.3
#     n_epochs: 5
#     gae_lambda: 0.98
#     max_grad_norm: 0.5
#     vf_coef: 0.28858950016892726
#     sde_sample_freq: 64
#     policy_kwargs: "dict(activation_fn=th.nn.Tanh, net_arch=[dict(pi=[64, 64], vf=[64, 64])])"

PumpStation3P-power-v1:
    normalize: true
    n_envs: 4
    n_timesteps: !!float 5e6
    policy: 'MlpPolicy'
    ent_coef: 0.0
    max_grad_norm: 0.5
    n_steps: 8
    gae_lambda: 0.9
    vf_coef: 0.4
    gamma: 0.99
    use_rms_prop: True
    normalize_advantage: False
    learning_rate: lin_7e-4
    use_sde: True
    policy_kwargs: "dict(log_std_init=-2, ortho_init=False)"

