# PumpStation-v0:
#   normalize: true
#   n_envs: 1
#   policy: 'MlpPolicy'
#   n_timesteps: !!float 50000
#   batch_size: 256
#   n_steps: 8
#   gamma: 0.9999
#   learning_rate: 5.05041e-05
#   ent_coef: 0.000585045
#   clip_range: 0.1
#   n_epochs: 20
#   gae_lambda: 0.95
#   max_grad_norm: 1
#   vf_coef: 0.871923


PumpStation-v0: 
    policy: 'MlpPolicy'
    normalize: true
    n_timesteps: 50000
    batch_size: 128
    n_steps: 2048
    gamma: 0.9999
    learning_rate: 0.0008868604628397997
    ent_coef: 5.51072732865457e-06
    clip_range: 0.2 
    n_epochs: 10 
    gae_lambda: 0.9
    max_grad_norm: 0.7
    vf_coef: 0.4663195286157188
    sde_sample_freq: 32
    # log_std_init: 0.009632546502040817
    # activation_fn: 'tanh'
    # net_arch: 'medium'

# {'batch_size': 128, 
# 'n_steps': 2048, 
# 'gamma': 0.9999, 
# 'learning_rate': 0.0008868604628397997, 
# 'ent_coef': 5.51072732865457e-06, 
# 'clip_range': 0.2, 
# 'n_epochs': 10, 
# 'gae_lambda': 0.9, 
# 'max_grad_norm': 0.7, 
# 'vf_coef': 0.4663195286157188,
# 'net_arch': 'tiny', '
# log_std_init': -2.5861223764945844, 
# 'sde_sample_freq': 32, 
# 'activation_fn': 'tanh'}

# {'batch_size': 256, 
# 'n_steps': 64, 
# 'gamma': 0.98, 
# 'learning_rate': 0.010793391045336956, 
# 'ent_coef': 7.02815680218493e-07, 
# 'clip_range': 0.1, 'n_epochs': 1, 'gae_lambda': 0.9, 
# 'max_grad_norm': 1, 
# 'vf_coef': 0.03538866484772407, 'net_arch': 'medium', 
# 'activation_fn': 'tanh'}

# {'batch_size': 512, 
# 'n_steps': 64, 
# 'gamma': 0.98, 
# 'learning_rate': 0.0004715401932112559, 
# 'ent_coef': 0.027689213719844546, 
# 'clip_range': 0.2, 
# 'n_epochs': 20, 
# 'gae_lambda': 0.92, 
# 'max_grad_norm': 0.7, 
# 'vf_coef': 0.9123561874119246, 
# 'net_arch': 'medium', 
# 'log_std_init': 0.009632546502040817, 
# 'sde_sample_freq': 32, 
# 'activation_fn': 'tanh'}
PumpStation3P-v0: 
    policy: 'MlpPolicy'
    normalize: true
    n_timesteps: 50000
    batch_size: 128
    n_steps: 2048
    gamma: 0.9999
    learning_rate: 0.0008868604628397997
    ent_coef: 5.51072732865457e-06
    clip_range: 0.2 
    n_epochs: 10 
    gae_lambda: 0.9
    max_grad_norm: 0.7
    vf_coef: 0.4663195286157188
    sde_sample_freq: 32
    # log_std_init: 0.009632546502040817
    # activation_fn: 'tanh'
    # net_arch: 'medium'